version: '2'

services:
  backend:
    image: 'backend:latest'
    build:
      context: .
    container_name: backend
    depends_on:
      - db
    ports:
      - '8080:8080'

  db:
    image: 'postgres:alpine'
    ports:
      - '5432:5432'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=darius
      - POSTGRES_DB=FoodOrderingApplication